export type Place = {
  name: string
  category: '카페' | '식당' | '바' | '활동' | '쇼핑'
  description: string
  price_range: string
  vibe: string[]
  address: string
  google_maps_url: string
}

export const SEONGSU_PLACES: Place[] = [
  // 카페
  {
    name: '어니언 성수',
    category: '카페',
    description: '폐공장을 개조한 빈티지 베이커리 카페. 높은 천장과 넓은 공간, 갓 구운 빵과 스페셜티 커피가 유명. 인스타 감성 최고, 성수 대표 카페.',
    price_range: '1-2만원',
    vibe: ['핫플', '감성적', '인스타'],
    address: '서울 성동구 아차산로9길 8',
    google_maps_url: 'https://maps.app.goo.gl/onion-seongsu',
  },
  {
    name: '블루보틀 성수',
    category: '카페',
    description: '미니멀한 인테리어의 스페셜티 커피 전문점. 조용하고 세련된 분위기. 싱글오리진 커피를 천천히 즐기기 좋음.',
    price_range: '1만원',
    vibe: ['감성적', '조용한'],
    address: '서울 성동구 왕십리로2길 20',
    google_maps_url: 'https://maps.app.goo.gl/bluebottle-seongsu',
  },
  {
    name: '대림창고',
    category: '카페',
    description: '1970년대 창고를 개조한 대형 복합문화공간. 카페와 팝업스토어 동시 운영. 대규모 브랜드 팝업이 자주 열려 항상 새로운 볼거리가 있음.',
    price_range: '1-2만원',
    vibe: ['핫플', '활동적', '팝업'],
    address: '서울 성동구 성수이로 78',
    google_maps_url: 'https://maps.app.goo.gl/daelim-changgo',
  },
  {
    name: '성수연방',
    category: '카페',
    description: '여러 트렌디한 브랜드가 모인 복합 쇼핑/카페 공간. 팝업스토어와 편집숍이 가득. 커피 한 잔 하며 쇼핑도 동시에 가능.',
    price_range: '1-3만원',
    vibe: ['핫플', '활동적', '팝업', '쇼핑'],
    address: '서울 성동구 연무장15길 11',
    google_maps_url: 'https://maps.app.goo.gl/seongsu-yeonbang',
  },
  {
    name: '카페 할아버지공장',
    category: '카페',
    description: '오래된 공장 구조물과 초록 식물이 조화를 이루는 감성 카페. 야외 공간이 넓어 날씨 좋은 날 최고. 사진찍기 좋은 포토스팟 다수.',
    price_range: '1만원',
    vibe: ['감성적', '인스타'],
    address: '서울 성동구 성수이로7가길 19',
    google_maps_url: 'https://maps.app.goo.gl/halabeoji-factory',
  },
  {
    name: '아크앤북 성수',
    category: '카페',
    description: '서점과 카페가 결합된 복합 문화공간. 책을 고르며 커피를 즐기는 감성적인 공간. 조용하고 여유로운 시간을 보내기에 최적.',
    price_range: '1만원',
    vibe: ['감성적', '조용한'],
    address: '서울 성동구 아차산로17길 48',
    google_maps_url: 'https://maps.app.goo.gl/arcnbook-seongsu',
  },
  {
    name: '카페 온더플레이트',
    category: '카페',
    description: '에그베네딕트, 아보카도 토스트 등 브런치 메뉴가 맛있는 카페. 건강하고 예쁜 플레이팅으로 인기. 주말 브런치 장소로 최적.',
    price_range: '1-2만원',
    vibe: ['감성적', '브런치'],
    address: '서울 성동구 성수일로 77',
    google_maps_url: 'https://maps.app.goo.gl/ontheplate-seongsu',
  },
  {
    name: '메쉬커피',
    category: '카페',
    description: '성수 로스터리 커피 전문점. 직접 로스팅한 원두로 만드는 커피 맛이 뛰어남. 커피 좋아하는 사람들에게 필수 방문 코스.',
    price_range: '1만원',
    vibe: ['조용한', '커피'],
    address: '서울 성동구 왕십리로 115',
    google_maps_url: 'https://maps.app.goo.gl/mesh-coffee',
  },

  // 식당
  {
    name: '라꼼마 성수',
    category: '식당',
    description: '성수에서 분위기 좋기로 유명한 이탈리안 레스토랑. 파스타와 피자가 맛있고 와인 페어링도 훌륭. 데이트 저녁 장소로 인기.',
    price_range: '2-3만원',
    vibe: ['감성적', '데이트', '로맨틱'],
    address: '서울 성동구 성수이로 89',
    google_maps_url: 'https://maps.app.goo.gl/lakomma-seongsu',
  },
  {
    name: '식물',
    category: '식당',
    description: '식물로 가득한 인테리어가 특징인 한식 레스토랑. 건강한 제철 재료를 사용한 다양한 한식 메뉴. 아늑하고 편안한 분위기.',
    price_range: '2만원',
    vibe: ['감성적', '조용한', '한식'],
    address: '서울 성동구 성수이로12길 33',
    google_maps_url: 'https://maps.app.goo.gl/sikmul-seongsu',
  },
  {
    name: '알베르 성수',
    category: '식당',
    description: '유럽 스타일의 감성 비스트로. 와인과 잘 어울리는 요리들로 구성. 저녁 분위기가 특히 좋아 특별한 날 방문하기 딱 좋음.',
    price_range: '3-5만원',
    vibe: ['로맨틱', '데이트', '감성적'],
    address: '서울 성동구 왕십리로2길 7',
    google_maps_url: 'https://maps.app.goo.gl/albert-seongsu',
  },
  {
    name: '오우 성수',
    category: '식당',
    description: '성수 핫플 맛집. 트렌디한 공간에서 즐기는 퓨전 요리. 감각적인 인테리어와 맛있는 음식으로 항상 웨이팅이 있음.',
    price_range: '2-3만원',
    vibe: ['핫플', '활동적'],
    address: '서울 성동구 성수이로16길 54',
    google_maps_url: 'https://maps.app.goo.gl/ouw-seongsu',
  },
  {
    name: '투뿔등심 성수',
    category: '식당',
    description: '가성비 좋은 한우 정육식당. 직접 구워 먹는 신선한 고기. 친구들과 함께 실컷 먹기 좋은 곳.',
    price_range: '2-4만원',
    vibe: ['활동적', '친구', '고기'],
    address: '서울 성동구 성수이로 96',
    google_maps_url: 'https://maps.app.goo.gl/twobull-seongsu',
  },
  {
    name: '서울숲 브루어리',
    category: '식당',
    description: '서울숲 근처의 크래프트 맥주 펍. 직접 양조한 다양한 맥주와 함께 즐기는 안주. 친구들 모임이나 가벼운 저녁 식사에 최적.',
    price_range: '2-3만원',
    vibe: ['활동적', '친구', '맥주'],
    address: '서울 성동구 뚝섬로1나길 5',
    google_maps_url: 'https://maps.app.goo.gl/seoul-forest-brewery',
  },
  {
    name: '성수 연어',
    category: '식당',
    description: '신선한 연어 오마카세와 회 전문점. 합리적인 가격에 퀄리티 높은 해산물 요리. 특별한 날 가기 좋은 고급스러운 분위기.',
    price_range: '3-5만원',
    vibe: ['감성적', '데이트', '특별한날'],
    address: '서울 성동구 성수이로20길 16',
    google_maps_url: 'https://maps.app.goo.gl/seongsu-salmon',
  },

  // 바
  {
    name: '스트레인저스 바',
    category: '바',
    description: '성수 대표 칵테일 바. 시그니처 칵테일 메뉴가 다양하고 바텐더의 실력이 뛰어남. 늦은 밤 분위기가 특히 좋음.',
    price_range: '2-3만원',
    vibe: ['핫플', '로맨틱', '야간'],
    address: '서울 성동구 성수이로7가길 9',
    google_maps_url: 'https://maps.app.goo.gl/strangers-bar',
  },
  {
    name: '더 퍼스트 펭귄',
    category: '바',
    description: '성수 힙한 분위기의 대표 펍. 크래프트 맥주와 칵테일이 다양. 주말 저녁엔 항상 활기차고 신나는 분위기.',
    price_range: '2-3만원',
    vibe: ['핫플', '활동적', '친구'],
    address: '서울 성동구 성수이로 116',
    google_maps_url: 'https://maps.app.goo.gl/first-penguin',
  },
  {
    name: '루프탑 바 성수',
    category: '바',
    description: '성수동 전경이 한눈에 보이는 루프탑 바. 해질 무렵 방문하면 환상적인 뷰. 칵테일과 와인이 주 메뉴. 예약 추천.',
    price_range: '3-5만원',
    vibe: ['로맨틱', '데이트', '뷰맛집'],
    address: '서울 성동구 왕십리로 130',
    google_maps_url: 'https://maps.app.goo.gl/rooftop-bar-seongsu',
  },

  // 활동/명소
  {
    name: '서울숲',
    category: '활동',
    description: '성수 대표 도심 공원. 피크닉, 산책, 자전거 타기에 최적. 사슴 방사장과 나비 정원도 있음. 날씨 좋은 날 꼭 가야 하는 곳.',
    price_range: '무료',
    vibe: ['활동적', '자연', '피크닉'],
    address: '서울 성동구 뚝섬로 273',
    google_maps_url: 'https://maps.app.goo.gl/seoul-forest',
  },
  {
    name: '언더스탠드에비뉴',
    category: '쇼핑',
    description: '컨테이너로 만든 야외 쇼핑몰. 독립 브랜드 편집숍, 카페, 식당이 모여 있음. 가볍게 구경하며 걷기 좋은 공간.',
    price_range: '무료~2만원',
    vibe: ['활동적', '쇼핑', '핫플'],
    address: '서울 성동구 왕십리로 83',
    google_maps_url: 'https://maps.app.goo.gl/understand-avenue',
  },
  {
    name: '성수 카카오프렌즈',
    category: '쇼핑',
    description: '카카오 캐릭터 굿즈와 포토존으로 가득한 플래그십 스토어. 다양한 MD 상품 쇼핑과 귀여운 사진 찍기에 좋음.',
    price_range: '1-2만원',
    vibe: ['활동적', '귀여운', '쇼핑'],
    address: '서울 성동구 아차산로 113',
    google_maps_url: 'https://maps.app.goo.gl/kakao-friends-seongsu',
  },
  {
    name: '성수 뚝섬한강공원',
    category: '활동',
    description: '한강변 공원. 자전거 대여, 피크닉, 일몰 감상에 최적. 편의점에서 치킨과 맥주 사서 즐기는 한강 피크닉 코스.',
    price_range: '무료',
    vibe: ['활동적', '자연', '피크닉', '로맨틱'],
    address: '서울 성동구 강변북로 139',
    google_maps_url: 'https://maps.app.goo.gl/ttukseom-hangang',
  },
]
